### PR TITLE
Likes

### PR DESCRIPTION
**Pull request by kharesiddhant**
**#What**
- I've added the functionality for a user to like a post in this branch. Font awesome library is used for the like icon. 

**#Why**
- The like provides the user to like a post. Will also add a feature that allows the user to view their liked posts.

**#How**
- Filter the user's like out of all the likes on the post from the model Like and store it in the like object (if it exists).
- The first condition in **views.route(/like-post/<post_id>)** checks if the post exists or not. Flash message if post doesn't exist.
- Otherwise if like object exists already, meaning the user has already liked the post earlier and the filtered object returns true. Delete the like as the like_post method is fired again.
- Finally, if the like object returns false, meaning the user has not liked the post, then create a like object in the Like model.
- This allows the like icon to behave like a toggle button.
- The counter at the left of the icon represents the length of the Like model from the database.

**#Screenshots**
- **Post that has not been liked**
image
- **Liked Post**
image

### CODE REVIEW

**Comment by AnjanJ** [comment]
@Sidkjr If you click on heart again, Does it unlike the post ???

**Review by AnjanJ — APPROVED** [review]
Again the bin files are showing in the diff.

**Comment by kharesiddhant** [comment]
> @Sidkjr If you click on heart again, Does it unlike the post ???

Yes

**Comment by kharesiddhant** [comment]
> Again the bin files are showing in the diff.

Yes, These changes are due to refreshing the file index after using 
`git rm -r --cached`

These cache changes are thus not visible in later commits from now. Meaning now they are successfully recognized by .gitignore

**Pull request merged**
